from numpy import Infinity
from enum import IntEnum

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
RED = (255, 0, 0)
BOARD_COLOUR = (240,210,80)

DEEP = 1
BLOCK_WIDTH = 28
BLOCKS = 16    # 16
SCREEN_WIDTH = BLOCKS*BLOCK_WIDTH + 10
SCREEN_HEIGHT = BLOCKS*BLOCK_WIDTH + 10

POS_INF = Infinity
NEG_INF = -Infinity

AI_DEPTH = 2
#对状况评分常量
class Score():
    ONE = 10
    TWO = 100
    THREE = 1000
    FOUR = 100000
    FIVE = Infinity
    BLOCKED_ONE = 1
    BLOCKED_TWO = 10
    BLOCKED_THREE = 100
    BLOCKED_FOUR = 10000
    
class CHESS_TYPE():
	NONE = 0
	SLEEP_TWO = 1
	LIVE_TWO = 2
	SLEEP_THREE = 3
	LIVE_THREE = 4
	CHONG_FOUR = 5
	LIVE_FOUR = 6
	LIVE_FIVE = 7

CHESS_TYPE_NUM = 8
FIVE = CHESS_TYPE.LIVE_FIVE
FOUR, THREE, TWO = CHESS_TYPE.LIVE_FOUR, CHESS_TYPE.LIVE_THREE, CHESS_TYPE.LIVE_TWO
SFOUR, STHREE, STWO = CHESS_TYPE.CHONG_FOUR, CHESS_TYPE.SLEEP_THREE, CHESS_TYPE.SLEEP_TWO
